Display interest rates in percent
agoenergy/ptx-boa pull request #306
Opened 2024-04-04 14:49 UTC by joAschauer

Fixes #261

2024-04-16 07:44 UTC, markushal commented
- efficiencies of electrolyzers are still per unit: 
![grafik](https://github.com/agoenergy/ptx-boa/assets/26714648/6586f7ef-0141-429e-960c-87f718401e9a)

- interest rates are in percent now, but can the number display be formatted so that a percent sign appears after the number? (e.g 5.23% instead of 5.23)
![grafik](https://github.com/agoenergy/ptx-boa/assets/26714648/f4a4e25e-3379-43cd-92b9-61c55d30737e)

2024-04-16 07:46 UTC, markushal requested changes
Hi Jo, check out the comment I wrote

2024-05-13 12:12 UTC, markushal requested changes
Thanks! If you could now use the % format in the map legend as well, that would be perfect

![grafik](https://github.com/agoenergy/ptx-boa/assets/26714648/01a8eeaa-62ef-4e57-8719-a627faa74780)

2024-05-15 08:52 UTC, markushal requested changes
thanks! I am so sorry, but there is one other place where it still says "per unit":

![grafik](https://github.com/agoenergy/ptx-boa/assets/26714648/eed7d9d0-47e8-47f2-8b74-63469d0e7a88)

2024-05-15 11:53 UTC, joAschauer commented on app/user_data.py
> +            [st.session_state["user_changes_df"].astype(res.dtypes), res]
fixes #380

2024-05-15 12:51 UTC, markushal commented on app/user_data.py
> +            [st.session_state["user_changes_df"].astype(res.dtypes), res]
nice, thanks!

2024-05-15 12:53 UTC, markushal approved these changes

2024-05-15 12:53 UTC, merged