86 implement comparison sheets
agoenergy/ptx-boa pull request #89
Opened 2023-11-13 15:52 UTC by markushal

2023-11-13 18:10 UTC, joAschauer requested changes
the option "10 cheapest" does not make sense for "Costs by data scenario" and "Costs by renewable electricity source". We could think about removing this. Otherwise looks good!

2023-11-13 18:11 UTC, joAschauer approved these changes

2023-11-14 08:11 UTC, markushal commented
> the option "10 cheapest" does not make sense for "Costs by data scenario" and "Costs by renewable electricity source". We could think about removing this. Otherwise looks good!

You are so right. I fixed this, and also added the option to highlight the current selection in the bar plots. Fine like this?

2023-11-14 08:13 UTC, merged

2023-11-14 08:15 UTC, markushal commented
@joAschauer : You approved the PR yesterday. I added three new commit today and was able to merge the complete PR just now, including the three new commits. Isnt it strange that you did not need to review them?